#ifndef _SETTINGS_H
#define _SETTINGS_H

// #define DEBUG_NOTE_ON
// #define DEBUG_NOTE_OFF
// #define DEBUG_NOTE_DETAILS
// #define DEBUG_PITCH_BEND
// #define DEBUG_PITCH_BEND_DETAILS
// #define DEBUG_PROGRAM_CHANGE
// #define DEBUG_PROGRAM_CHANGE_DETAILS
// #define DEBUG_CONTROL_CHANGE
// #define DEBUG_AFTER_TOUCH_POLY
// #define DEBUG_AFTER_TOUCH_CHANNEL
// #define DEBUG_SYSTEM_COMMON
// #define DEBUG_REALTIME
// #define DEBUG_RESET
#endif