#ifndef _SETTINGS_H
#define _SETTINGS_H

// #define DEBUG_NOTE
// #define DEBUG_NOTE_DETAILS
// #define DEBUG_PITCH_BEND
// #define DEBUG_PITCH_BEND_DETAILS
#define DEBUG_PROGRAM_CHANGE
#define DEBUG_PROGRAM_CHANGE_DETAILS
// #define DEBUG_CONTROL_CHANGE
#endif